# Generated by Django 5.2.16 on 2026-08-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=150)),
                ('procedure_area', models.CharField(max_length=100)),
                ('procedure_date', models.DateField()),
                ('clinician_note', models.TextField()),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('WAITING_PATIENT', '환자 확인 대기'), ('READY_TO_TRANSFER', '전송 동의 대기'), ('TRANSFERRED', '전송 완료')], default='WAITING_PATIENT', max_length=30)),
                ('procedure_info_agreed', models.BooleanField(default=False)),
                ('adverse_effect_info_agreed', models.BooleanField(default=False)),
                ('overseas_transfer_agreed', models.BooleanField(default=False)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('partner_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=150)),
                ('medical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cases.medicalcase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medical_case', 'ingredient_name'), name='unique_case_ingredient')],
            },
        ),
        migrations.CreateModel(
            name='CaseAdverseEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('SWELLING', '부종'), ('INFLAMMATION', '염증'), ('PAIN', '통증'), ('REDNESS', '붉어짐'), ('INFECTION', '감염 의심'), ('PIGMENTATION', '색소침착')], max_length=30)),
                ('medical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_effects', to='cases.medicalcase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medical_case', 'effect_type'), name='unique_case_adverse_effect')],
            },
        ),
    ]
