# Generated by Django 5.2.16 on 2026-08-06 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('medical_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_rooms', to='cases.medicalcase')),
                ('partner_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_case_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='cases.casechatroom')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='casechatroom',
            constraint=models.UniqueConstraint(fields=('medical_case', 'partner_hospital'), name='unique_case_partner_chat_room'),
        ),
        migrations.AddIndex(
            model_name='casechatmessage',
            index=models.Index(fields=['chat_room', 'id'], name='chat_room_message_idx'),
        ),
    ]
