# Generated by Django 5.2.16 on 2026-08-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casechatroom_casechatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casechatmessage',
            name='source_language',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.CreateModel(
            name='CaseChatMessageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('translated_content', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', '번역 중'), ('COMPLETED', '번역 완료'), ('FAILED', '번역 실패')], default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='cases.casechatmessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'target_language'), name='unique_message_target_language')],
            },
        ),
    ]
