# Generated by Django 5.2.16 on 2026-08-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casechatmessage_source_language_and_more'),
        ('selfsymptoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSyncRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_gender', models.CharField(choices=[('FEMALE', '여성'), ('MALE', '남성'), ('OTHER', '기타')], max_length=20)),
                ('patient_birth_date', models.DateField()),
                ('selection_source', models.CharField(choices=[('AI_RECOMMENDATION', 'AI 추천'), ('NETWORK', '네트워크 병원 목록')], max_length=30)),
                ('status', models.CharField(choices=[('REQUESTED', '시술 병원 검토 대기'), ('HOSPITAL_REVIEWED', '시술 병원 검토 완료'), ('PATIENT_CONSENTED', '환자 전송 동의 완료'), ('SENT_TO_PARTNER', '상대 병원 전송 완료'), ('COMPLETED', '협진 수락 완료'), ('CANCELLED', '취소')], default='REQUESTED', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_request', to='cases.medicalcase')),
                ('origin_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_case_sync_requests', to=settings.AUTH_USER_MODEL)),
                ('partner_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_case_sync_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_sync_requests', to=settings.AUTH_USER_MODEL)),
                ('symptom_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_requests', to='selfsymptoms.patientsymptomcase')),
            ],
        ),
    ]
