# Generated by Django 5.2.16 on 2026-08-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casesyncrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', '협진 요청'), ('ACCEPTED', '협진 수락'), ('REJECTED', '협진 거절'), ('CANCELLED', '협진 취소')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collaboration_request', to='cases.medicalcase')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
    ]
