# Generated by Django 5.2.16 on 2026-08-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casecollaborationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgment_draft', models.TextField()),
                ('evidence_items', models.JSONField(default=list)),
                ('observation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_upload_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, default='')),
                ('patient_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('AI_DRAFT', 'AI 정리 초안'), ('IN_REVIEW', '의료진 검토 중'), ('FINAL', '최종 합의')], default='AI_DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_requested_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='cases.casechatroom')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_case_agreements', to=settings.AUTH_USER_MODEL)),
                ('revision_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_agreement_revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseAgreementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('previous_data', models.JSONField()),
                ('changed_fields', models.JSONField(default=list)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cases.caseagreement')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_agreement_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='CaseAgreementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_version', models.PositiveIntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cases.caseagreement')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_agreement_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agreement', 'hospital'), name='unique_agreement_hospital_review')],
            },
        ),
    ]
