# Generated by Django 5.2.16 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_unify_case_transfer_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="casecollaborationrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="casecollaborationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "협진 요청"),
                    ("ACCEPTED", "협진 수락"),
                    ("COMPLETED", "협진 완료"),
                    ("REJECTED", "협진 거절"),
                    ("CANCELLED", "협진 취소"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
