# Generated by Django 5.2.16 on 2026-08-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_collaboration_completion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseAdverseEffect',
        ),
    ]
