# Generated by Django 5.2.16 on 2026-08-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_collaboration_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecollaborationrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
