# Generated by Django 5.2.16 on 2026-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_delete_caseadverseeffect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetransfer',
            name='adverse_effect_clinician_note_agreed',
        ),
        migrations.RemoveField(
            model_name='casetransfer',
            name='overseas_ai_processing_agreed',
        ),
        migrations.RemoveField(
            model_name='casetransfer',
            name='procedure_medication_agreed',
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='information_items_purpose_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='medical_consultation_use_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='personal_information_provision_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='withdrawal_right_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
