# Generated by Django 5.2.16 on 2026-08-16 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_delete_caseadverseeffect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='cases.casechatroom')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_chat_read_states', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='read_by_states', to='cases.casechatmessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat_room', 'hospital'), name='unique_chat_room_hospital_read_state')],
            },
        ),
    ]
