# Generated by Django 5.2.16 on 2026-08-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_casecollaborationrequest_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecollaborationrequest',
            name='cancelled_at',
        ),
    ]
