# Generated by Django 5.2.16 on 2026-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_casechatreadstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetransfer',
            name='patient_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casetransfer',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('FEMALE', '여성'), ('MALE', '남성'), ('OTHER', '기타')], max_length=20, null=True),
        ),
    ]
