# Generated by Django 5.2.16 on 2026-08-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSymptomCase',
            fields=[
                ('symptom_case_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symptom_start_date', models.DateField(blank=True, null=True)),
                ('onset_timing', models.CharField(blank=True, choices=[('IMMEDIATE', '즉시'), ('AFTER_1_DAY', '1일 후'), ('AFTER_2_3_DAYS', '2~3일 후'), ('AFTER_4_7_DAYS', '4~7일 후'), ('AFTER_1_WEEK', '1주 이후'), ('UNKNOWN', '정확히 모름')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '작성 중'), ('SUBMITTED', '작성 완료'), ('MATCHING', '병원 매칭 중'), ('HOSPITAL_SELECTED', '병원 선택 완료'), ('CONNECTION_REQUESTED', '연결 요청 완료'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_cases', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'PATIENT_SYMPTOM_CASE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSymptomArea',
            fields=[
                ('symptom_area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_type', models.CharField(choices=[('FACE', '얼굴 전체'), ('FOREHEAD', '이마'), ('EYE', '눈'), ('NOSE', '코'), ('CHEEK', '볼'), ('MOUTH', '입술 및 입 주변'), ('CHIN', '턱'), ('NECK', '목'), ('CHEST', '가슴'), ('ABDOMEN', '복부'), ('ARM', '팔'), ('HAND', '손'), ('LEG', '다리'), ('FOOT', '발'), ('OTHER', '기타')], max_length=30)),
                ('custom_area', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='selfsymptoms.patientsymptomcase')),
            ],
            options={
                'db_table': 'PATIENT_SYMPTOM_AREA',
                'constraints': [models.UniqueConstraint(fields=('symptom_case', 'area_type'), name='unique_symptom_area')],
            },
        ),
        migrations.CreateModel(
            name='PatientSymptomImage',
            fields=[
                ('symptom_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='symptom_images/%Y/%m/%d/')),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='selfsymptoms.patientsymptomcase')),
            ],
            options={
                'db_table': 'PATIENT_SYMPTOM_IMAGE',
                'ordering': ['display_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('symptom_case', 'display_order'), name='unique_symptom_image_order')],
            },
        ),
        migrations.CreateModel(
            name='PatientSymptomType',
            fields=[
                ('symptom_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symptom_type', models.CharField(choices=[('REDNESS', '붉음'), ('SWELLING', '붓기'), ('PAIN', '통증'), ('BRUISING', '멍'), ('BLEEDING', '출혈'), ('DISCHARGE', '분비물'), ('ITCHING', '가려움'), ('HEAT', '열감'), ('NUMBNESS', '감각 저하'), ('ASYMMETRY', '비대칭'), ('WOUND_OPENING', '상처 벌어짐'), ('OTHER', '기타')], max_length=30)),
                ('custom_symptom', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_types', to='selfsymptoms.patientsymptomcase')),
            ],
            options={
                'db_table': 'PATIENT_SYMPTOM_TYPE',
                'constraints': [models.UniqueConstraint(fields=('symptom_case', 'symptom_type'), name='unique_symptom_type')],
            },
        ),
    ]
