# Generated by Django 5.2.16 on 2026-08-14 07:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitalprofile_language_code'),
        ('selfsymptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsymptomcase',
            name='diagnosed_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosed_symptom_types', to='accounts.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='patientsymptomcase',
            name='diagnosis_document',
            field=models.FileField(blank=True, null=True, upload_to='diagnosis_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='PDF, JPG, JPEG, PNG 파일만 업로드 가능합니다.')]),
        ),
    ]
