# Generated by Django 5.2.16 on 2026-08-14 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitalprofile_language_code'),
        ('selfsymptoms', '0002_patientsymptomcase_diagnosed_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsymptomcase',
            name='diagnosed_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosed_symptom_cases', to='accounts.hospitalprofile'),
        ),
        migrations.CreateModel(
            name='DiagnosisAnalysis',
            fields=[
                ('diagnosis_analysis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_analysis', to='selfsymptoms.patientsymptomcase')),
            ],
            options={
                'db_table': 'DIAGNOSIS_ANALYSIS',
            },
        ),
    ]
