# Generated by Django 5.2.16 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "selfsymptoms",
            "0003_alter_patientsymptomcase_diagnosed_hospital_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientsymptomcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "작성 중"),
                    ("SUBMITTED", "작성 완료"),
                    ("MATCHING", "병원 매칭 중"),
                    ("HOSPITAL_SELECTED", "병원 선택 완료"),
                    ("CONNECTION_REQUESTED", "연결 요청 완료"),
                    ("IN_COLLABORATION", "협진 진행 중"),
                    ("COMPLETED", "완료"),
                    ("CANCELLED", "취소"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
    ]
