# Generated by Django 5.2.16 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfsymptoms', '0004_add_in_collaboration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsymptomarea',
            name='custom_area',
        ),
        migrations.AlterField(
            model_name='patientsymptomarea',
            name='area_type',
            field=models.CharField(choices=[('FACE', '얼굴 전체'), ('FOREHEAD', '이마'), ('EYE', '눈'), ('NOSE', '코'), ('CHEEK', '볼'), ('MOUTH', '입술 및 입 주변'), ('CHIN', '턱'), ('NECK', '목'), ('CHEST', '가슴'), ('ABDOMEN', '복부'), ('ARM', '팔'), ('HAND', '손'), ('LEG', '다리'), ('FOOT', '발')], max_length=30),
        ),
    ]
