# Generated by Django 5.2.16 on 2026-08-16 10:00

from django.db import migrations, models


def normalize_figma_choices(apps, schema_editor):
    symptom_case = apps.get_model(
        'selfsymptoms',
        'PatientSymptomCase',
    )
    symptom_type = apps.get_model(
        'selfsymptoms',
        'PatientSymptomType',
    )

    symptom_case.objects.filter(
        onset_timing__in=[
            'AFTER_1_DAY',
            'AFTER_2_3_DAYS',
            'AFTER_4_7_DAYS',
            'AFTER_1_WEEK',
        ],
    ).update(onset_timing='AFTER_DAYS')
    symptom_case.objects.filter(
        onset_timing='UNKNOWN',
    ).update(onset_timing=None)

    affected_case_ids = list(
        symptom_type.objects
        .filter(symptom_type__in=['BRUISING', 'BLEEDING'])
        .values_list('symptom_case_id', flat=True)
        .distinct()
    )

    for symptom_case_id in affected_case_ids:
        legacy_rows = symptom_type.objects.filter(
            symptom_case_id=symptom_case_id,
            symptom_type__in=['BRUISING', 'BLEEDING'],
        ).order_by('symptom_type_id')
        retained_row = legacy_rows.first()
        legacy_rows.exclude(pk=retained_row.pk).delete()
        retained_row.symptom_type = 'BRUISING_BLEEDING'
        retained_row.custom_symptom = None
        retained_row.save(
            update_fields=['symptom_type', 'custom_symptom'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('selfsymptoms', '0005_remove_patientsymptomarea_custom_area_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_figma_choices,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='patientsymptomcase',
            name='onset_timing',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', '시술 직후'), ('AFTER_DAYS', '시술 후 며칠 뒤')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientsymptomtype',
            name='symptom_type',
            field=models.CharField(choices=[('REDNESS', '붉음'), ('SWELLING', '붓기'), ('PAIN', '통증'), ('BRUISING_BLEEDING', '멍/출혈'), ('DISCHARGE', '분비물'), ('ITCHING', '가려움'), ('HEAT', '열감'), ('NUMBNESS', '감각 저하'), ('ASYMMETRY', '비대칭'), ('WOUND_OPENING', '상처 벌어짐'), ('OTHER', '기타')], max_length=30),
        ),
    ]
