# Generated by Django 5.2.16 on 2026-09-15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfsymptoms", "0006_alter_patientsymptomcase_onset_timing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomCaseAIRequestLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("HOSPITAL_MATCHING", "병원 추천"),
                            ("CASE_TRANSFER", "케이스 전송 준비"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symptom_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_request_locks",
                        to="selfsymptoms.patientsymptomcase",
                    ),
                ),
            ],
            options={
                "db_table": "SYMPTOM_CASE_AI_REQUEST_LOCK",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symptom_case", "operation"),
                        name="unique_symptom_case_ai_operation_lock",
                    ),
                ],
            },
        ),
    ]
