# Generated by Django 5.2.16 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfsymptoms", "0007_symptomcaseairequestlock"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisanalysis",
            name="analysis_language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="diagnosisanalysis",
            name="analysis_input_checksum",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
