# Generated by Django 5.2.16 on 2026-08-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospitalprofile_medicalspecialty'),
        ('accounts', '0004_user_preferred_language'),
    ]

    operations = [
    ]
