# Generated by Django 5.2.16 on 2026-08-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospitalprofile_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_info_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='residence_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
