# Generated by Django 5.2.16 on 2026-08-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patientprofile_city_patientprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='email',
        ),
    ]
