# Generated by Django 5.2.16 on 2026-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_patientprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='overseas_transfer_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
