# Generated by Django 5.2.16 on 2026-09-11 06:08

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_audit_numeric_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[accounts.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[accounts.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[accounts.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[accounts.validators.validate_longitude]),
        ),
        migrations.AddConstraint(
            model_name='hospitalprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), models.Q(('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='hospitalprofile_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), models.Q(('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='patientprofile_coordinates_valid'),
        ),
    ]
