"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

def get_required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()

    if not value:
        raise ImproperlyConfigured(
            f"Required environment variable is missing: {name}"
        )

    return value


def get_bool_env(
    name: str,
    *,
    default: bool | None = None,
) -> bool:
    value = os.environ.get(name)

    if value is None:
        if default is None:
            raise ImproperlyConfigured(
                f"Required environment variable is missing: {name}"
            )
        return default

    normalized = value.strip().lower()

    if normalized in {"true", "1", "yes", "on"}:
        return True

    if normalized in {"false", "0", "no", "off"}:
        return False

    raise ImproperlyConfigured(
        f"{name} must be true or false."
    )


def get_list_env(
    name: str,
    *,
    default: list[str] | None = None,
) -> list[str]:
    value = os.environ.get(name)

    if value is None:
        return default or []

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


IS_RENDER = bool(
    os.environ.get("RENDER")
    or os.environ.get("RENDER_EXTERNAL_HOSTNAME")
)

APP_ENV = os.environ.get(
    "APP_ENV",
    "production" if IS_RENDER else "development",
).strip().lower()

if APP_ENV not in {"development", "production"}:
    raise ImproperlyConfigured(
        "APP_ENV must be development or production."
    )

IS_PRODUCTION = APP_ENV == "production"

RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME",
    "",
).strip()



if IS_PRODUCTION:
    SECRET_KEY = get_required_env("SECRET_KEY")
    DEBUG = get_bool_env("DEBUG")

    if DEBUG:
        raise ImproperlyConfigured(
            "DEBUG must be false in production."
        )

    ALLOWED_HOSTS = get_list_env(
        "ALLOWED_HOSTS"
    )
    CORS_ALLOWED_ORIGINS = get_list_env(
        "CORS_ALLOWED_ORIGINS"
    )
    CORS_ALLOWED_ORIGIN_REGEXES = get_list_env(
        "CORS_ALLOWED_ORIGIN_REGEXES"
    )
    CSRF_TRUSTED_ORIGINS = get_list_env(
        "CSRF_TRUSTED_ORIGINS"
    )

    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS is required in production."
        )

    if not CORS_ALLOWED_ORIGINS:
        raise ImproperlyConfigured(
            "CORS_ALLOWED_ORIGINS is required in production."
        )

    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured(
            "CSRF_TRUSTED_ORIGINS is required in production."
        )
else:
    SECRET_KEY = os.environ.get(
        "SECRET_KEY",
        "django-insecure-local-development-only",
    )
    DEBUG = get_bool_env(
        "DEBUG",
        default=True,
    )

    ALLOWED_HOSTS = get_list_env(
        "ALLOWED_HOSTS",
        default=[
            "localhost",
            "127.0.0.1",
        ],
    )
    CORS_ALLOWED_ORIGINS = get_list_env(
        "CORS_ALLOWED_ORIGINS",
        default=[
            "http://localhost:5173",
        ],
    )
    CORS_ALLOWED_ORIGIN_REGEXES = get_list_env(
        "CORS_ALLOWED_ORIGIN_REGEXES"
    )
    CSRF_TRUSTED_ORIGINS = get_list_env(
        "CSRF_TRUSTED_ORIGINS",
        default=[
            "http://localhost:5173",
        ],
    )


if RENDER_EXTERNAL_HOSTNAME:
    if RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(
            RENDER_EXTERNAL_HOSTNAME
        )

    render_origin = (
        f"https://{RENDER_EXTERNAL_HOSTNAME}"
    )

    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(
            render_origin
        )



# Application definition

# Do not register cloudinary_storage here. Its collectstatic override uses the
# removed STATICFILES_STORAGE setting and is incompatible with Django 5.2.
# The media backend is loaded directly through STORAGES below.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    "corsheaders",
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    "cases",
    'selfsymptoms',
    'matching',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}


OPENAI_TRANSLATION_MODEL = os.environ.get(
    "OPENAI_TRANSLATION_MODEL",
    "gpt-5.6-terra",
)

OPENAI_AGREEMENT_MODEL = os.environ.get(
    "OPENAI_AGREEMENT_MODEL",
    OPENAI_TRANSLATION_MODEL,
)

OPENAI_MATCHING_MODEL = os.environ.get(
    "OPENAI_MATCHING_MODEL",
    OPENAI_TRANSLATION_MODEL,
)

OPENAI_DOCUMENT_MODEL = os.environ.get(
    "OPENAI_DOCUMENT_MODEL",
    OPENAI_TRANSLATION_MODEL,
)

REST_USE_JWT = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": (
                "django.db.backends.sqlite3"
            ),
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL")
CLOUDINARY_CREDENTIALS = {
    "CLOUD_NAME": os.environ.get(
        "CLOUDINARY_CLOUD_NAME"
    ),
    "API_KEY": os.environ.get(
        "CLOUDINARY_API_KEY"
    ),
    "API_SECRET": os.environ.get(
        "CLOUDINARY_API_SECRET"
    ),
}
CLOUDINARY_CONFIGURED = bool(
    CLOUDINARY_URL
    or all(CLOUDINARY_CREDENTIALS.values())
)
CLOUDINARY_STORAGE = (
    CLOUDINARY_CREDENTIALS
    if all(CLOUDINARY_CREDENTIALS.values())
    else {}
)

if (
    os.environ.get("RENDER")
    or RENDER_EXTERNAL_HOSTNAME
) and not CLOUDINARY_CONFIGURED:
    raise ImproperlyConfigured(
        "Cloudinary credentials are required on Render. "
        "Set CLOUDINARY_URL or all of "
        "CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, "
        "and CLOUDINARY_API_SECRET."
    )

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage."
            "MediaCloudinaryStorage"
            if CLOUDINARY_CONFIGURED
            else "django.core.files.storage."
            "FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
