# Generated by Django 5.2.16 on 2026-08-09 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_hospitalprofile_medicalspecialty'),
        ('selfsymptoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMatchRequest',
            fields=[
                ('match_request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('required_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty_weight', models.PositiveSmallIntegerField(default=50)),
                ('distance_weight', models.PositiveSmallIntegerField(default=50)),
                ('collaboration_weight', models.PositiveSmallIntegerField(default=50)),
                ('location_source', models.CharField(choices=[('PROFILE', '프로필 위치'), ('CUSTOM', '직접 지정')], default='PROFILE', max_length=20)),
                ('search_country', models.CharField(max_length=50)),
                ('search_city', models.CharField(blank=True, max_length=100, null=True)),
                ('search_address', models.CharField(blank=True, max_length=255, null=True)),
                ('search_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('search_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('ANALYZING', '분석 중'), ('COMPLETED', '분석 완료'), ('SELECTED', '병원 선택'), ('CANCELLED', '취소')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='accounts.patientprofile')),
                ('symptom_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='selfsymptoms.patientsymptomcase')),
            ],
            options={
                'db_table': 'HOSPITAL_MATCH_REQUEST',
            },
        ),
        migrations.CreateModel(
            name='HospitalRecommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_number', models.PositiveSmallIntegerField()),
                ('rank_number', models.PositiveSmallIntegerField()),
                ('specialty_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collaboration_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.hospitalprofile')),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='matching.hospitalmatchrequest')),
            ],
            options={
                'db_table': 'HOSPITAL_RECOMMENDATION',
            },
        ),
        migrations.CreateModel(
            name='HospitalConnectionRequest',
            fields=[
                ('connection_request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', '요청'), ('ACCEPTED', '승인'), ('REJECTED', '거절'), ('CANCELLED', '취소'), ('COMPLETED', '완료')], default='REQUESTED', max_length=30)),
                ('request_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='accounts.hospitalprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='accounts.patientprofile')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='matching.hospitalrecommendation')),
            ],
            options={
                'db_table': 'HOSPITAL_CONNECTION_REQUEST',
            },
        ),
        migrations.AddConstraint(
            model_name='hospitalrecommendation',
            constraint=models.UniqueConstraint(fields=('match_request', 'hospital'), name='unique_recommended_hospital'),
        ),
        migrations.AddConstraint(
            model_name='hospitalrecommendation',
            constraint=models.UniqueConstraint(fields=('match_request', 'rank_number'), name='unique_recommendation_rank'),
        ),
    ]
