# Generated by Django 5.2.16 on 2026-08-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_hospitalmatchrequest_required_specialty_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalConnectionRequest',
        ),
    ]
