# Generated by Django 5.2.16 on 2026-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_delete_hospitalconnectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmatchrequest',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalmatchrequest',
            name='information_items_purpose_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalmatchrequest',
            name='medical_consultation_use_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalmatchrequest',
            name='personal_information_provision_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalmatchrequest',
            name='withdrawal_right_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
