# Generated by Django 5.2.16 on 2026-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_hospitalmatchrequest_agreed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrecommendation',
            name='collaboration_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
