# Generated by Django 5.2.16 on 2026-09-11 06:08

import accounts.validators
import matching.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_numeric_constraints'),
        ('matching', '0007_alter_hospitalmatchrequest_search_country'),
        ('selfsymptoms', '0006_alter_patientsymptomcase_onset_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmatchrequest',
            name='collaboration_weight',
            field=models.PositiveSmallIntegerField(default=50, validators=[matching.validation.validate_weight]),
        ),
        migrations.AlterField(
            model_name='hospitalmatchrequest',
            name='distance_weight',
            field=models.PositiveSmallIntegerField(default=50, validators=[matching.validation.validate_weight]),
        ),
        migrations.AlterField(
            model_name='hospitalmatchrequest',
            name='search_latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[accounts.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='hospitalmatchrequest',
            name='search_longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[accounts.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='hospitalmatchrequest',
            name='specialty_weight',
            field=models.PositiveSmallIntegerField(default=50, validators=[matching.validation.validate_weight]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='batch_number',
            field=models.PositiveSmallIntegerField(validators=[matching.validation.validate_rank]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='collaboration_count',
            field=models.PositiveIntegerField(default=0, validators=[matching.validation.validate_count]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='collaboration_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[matching.validation.validate_score]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[matching.validation.validate_distance]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='distance_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[matching.validation.validate_score]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='rank_number',
            field=models.PositiveSmallIntegerField(validators=[matching.validation.validate_rank]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='specialty_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[matching.validation.validate_score]),
        ),
        migrations.AlterField(
            model_name='hospitalrecommendation',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[matching.validation.validate_score]),
        ),
        migrations.AddConstraint(
            model_name='hospitalmatchrequest',
            constraint=models.CheckConstraint(condition=models.Q(('search_latitude__gte', -90), ('search_latitude__isnull', False), ('search_latitude__lte', 90), ('search_longitude__gte', -180), ('search_longitude__isnull', False), ('search_longitude__lte', 180)), name='match_search_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='hospitalmatchrequest',
            constraint=models.CheckConstraint(condition=models.Q(('collaboration_weight__gte', 0), ('collaboration_weight__lte', 100), ('distance_weight__gte', 0), ('distance_weight__lte', 100), ('specialty_weight__gte', 0), ('specialty_weight__lte', 100), models.Q(('specialty_weight__gt', 0), ('distance_weight__gt', 0), ('collaboration_weight__gt', 0), _connector='OR')), name='match_weights_valid'),
        ),
        migrations.AddConstraint(
            model_name='hospitalrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('batch_number__gte', 1), ('batch_number__lte', 32767), ('collaboration_count__gte', 0), ('collaboration_count__lte', 2147483647), ('collaboration_score__gte', 0), ('collaboration_score__lte', 100), ('distance_score__gte', 0), ('distance_score__lte', 100), ('rank_number__gte', 1), ('rank_number__lte', 32767), ('specialty_score__gte', 0), ('specialty_score__lte', 100), ('total_score__gte', 0), ('total_score__lte', 100)), name='recommendation_numbers_valid'),
        ),
        migrations.AddConstraint(
            model_name='hospitalrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('distance_km__isnull', True), models.Q(('distance_km__gte', 0), ('distance_km__lte', 99999999.99)), _connector='OR'), name='recommendation_distance_valid'),
        ),
    ]
