from django.urls import path

from .views import (
    CaseAgreementDetailView,
    CaseAgreementReviewView,
    CaseAgreementRevisionListView,
    CaseAgreementRevisionRequestView,
    AdverseEffectUpdateView,
    CaseChatMessageListCreateView,
    CaseCollaborationRequestAcceptView,
    CaseCollaborationRequestDetailView,
    CaseCollaborationRequestListView,
    CaseTransferView,
    MedicalCaseDetailView,
    MedicalCaseListCreateView,
    CaseSyncRequestListCreateView,
    CaseSyncRequestReviewView,
)


urlpatterns = [
    path(
        "",
        MedicalCaseListCreateView.as_view(),
        name="case-list-create",
    ),
    path(
        "<int:case_id>/",
        MedicalCaseDetailView.as_view(),
        name="case-detail",
    ),
    path(
        "<int:case_id>/adverse-effects/",
        AdverseEffectUpdateView.as_view(),
        name="case-adverse-effects",
    ),
    path(
        "<int:case_id>/transfer/",
        CaseTransferView.as_view(),
        name="case-transfer",
    ),
    path(
    "<int:case_id>/chat/rooms/<int:room_id>/messages/",
    CaseChatMessageListCreateView.as_view(),
    name="case-chat-message-list-create",
    ),
    path(
    "sync-requests/",
    CaseSyncRequestListCreateView.as_view(),
    name="case-sync-request-list-create",
    ),
    path(
        "sync-requests/<int:sync_request_id>/review/",
        CaseSyncRequestReviewView.as_view(),
        name="case-sync-request-review",
    ),
    path(
    "collaboration-requests/",
    CaseCollaborationRequestListView.as_view(),
    name="collaboration-request-list",
    ),
    path(
        "collaboration-requests/<int:collaboration_request_id>/accept/",
        CaseCollaborationRequestAcceptView.as_view(),
        name="collaboration-request-accept",
    ),
    path(
        "collaboration-requests/<int:collaboration_request_id>/",
        CaseCollaborationRequestDetailView.as_view(),
        name="collaboration-request-detail",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/",
        CaseAgreementDetailView.as_view(),
        name="case-agreement-detail",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/review/",
        CaseAgreementReviewView.as_view(),
        name="case-agreement-review",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/revisions/",
        CaseAgreementRevisionListView.as_view(),
        name="case-agreement-revision-list",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/revision-request/",
        CaseAgreementRevisionRequestView.as_view(),
        name="case-agreement-revision-request",
    ),
]