from django.urls import path

from .views import (
    CaseAgreementGenerateView,
    CaseAgreementDetailView,
    CaseAgreementReviewView,
    CaseAgreementRevisionListView,
    CaseChatMessageListCreateView,
    CaseChatRoomListView,
    CaseChatRoomReadView,
    CaseCollaborationRequestAcceptView,
    CaseCollaborationRequestDetailView,
    CaseCollaborationRequestListView,
    MedicalCaseDetailView,
    MedicalCaseListView,
    CaseTransferListCreateView,
    CaseTransferDetailView,
    CaseTransferReviewView,
    CaseTransferSendView,
    HospitalDashboardView,
    PartnerCaseTransferListView,
    PartnerCaseTransferDetailView,
    PatientProcedureHistoryListView,
    PatientProcedureHistoryDetailView,
)


urlpatterns = [
    path(
        "procedure-histories/",
        PatientProcedureHistoryListView.as_view(),
        name="patient-procedure-history-list",
    ),
    path(
        "procedure-histories/<int:medical_case_id>/",
        PatientProcedureHistoryDetailView.as_view(),
        name="patient-procedure-history-detail",
    ),
    path(
        "chat/rooms/",
        CaseChatRoomListView.as_view(),
        name="case-chat-room-list",
    ),
    path(
        "chat/rooms/<int:room_id>/read/",
        CaseChatRoomReadView.as_view(),
        name="case-chat-room-read",
    ),
    path(
        "hospital/dashboard/",
        HospitalDashboardView.as_view(),
        name="hospital-dashboard",
    ),
    path(
        "",
        MedicalCaseListView.as_view(),
        name="case-list",
    ),
    path(
        "<int:case_id>/",
        MedicalCaseDetailView.as_view(),
        name="case-detail",
    ),
    path(
    "<int:case_id>/chat/rooms/<int:room_id>/messages/",
    CaseChatMessageListCreateView.as_view(),
    name="case-chat-message-list-create",
    ),
    path(
    "collaboration-requests/",
    CaseCollaborationRequestListView.as_view(),
    name="collaboration-request-list",
    ),
    path(
        "collaboration-requests/<int:collaboration_request_id>/accept/",
        CaseCollaborationRequestAcceptView.as_view(),
        name="collaboration-request-accept",
    ),
    path(
        "collaboration-requests/<int:collaboration_request_id>/",
        CaseCollaborationRequestDetailView.as_view(),
        name="collaboration-request-detail",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/generate/",
        CaseAgreementGenerateView.as_view(),
        name="case-agreement-generate",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/",
        CaseAgreementDetailView.as_view(),
        name="case-agreement-detail",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/review/",
        CaseAgreementReviewView.as_view(),
        name="case-agreement-review",
    ),
    path(
        "<int:case_id>/chat/rooms/<int:room_id>/agreement/revisions/",
        CaseAgreementRevisionListView.as_view(),
        name="case-agreement-revision-list",
    ),
    path(
        "transfers/",
        CaseTransferListCreateView.as_view(),
        name="case-transfer-list-create",
    ),
    path(
        "transfers/<int:transfer_id>/",
        CaseTransferDetailView.as_view(),
        name="case-transfer-detail",
    ),
    path(
        "transfers/<int:transfer_id>/review/",
        CaseTransferReviewView.as_view(),
        name="case-transfer-review",
    ),
    path(
        "transfers/<int:transfer_id>/send/",
        CaseTransferSendView.as_view(),
        name="case-transfer-send",
    ),
    path(
        "transfers/received/",
        PartnerCaseTransferListView.as_view(),
        name="partner-case-transfer-list",
    ),
    path(
        "transfers/received/<int:transfer_id>/",
        PartnerCaseTransferDetailView.as_view(),
        name="partner-case-transfer-detail",
    ),
]
